---
apiVersion: v1
kind: Secret
metadata:
  name: git-ent-secret
  annotations:
    tekton.dev/git-0: https://github.com # Described below
type: kubernetes.io/basic-auth
stringData:
  username: "x-oauth-basic"
  password: "<oauth>"
---
apiVersion: v1
kind: Secret
data:
  .dockerconfigjson: <base64 dockerconfig.json>
metadata:
  name: registry-access-secret
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gs-access-svcaccount
secrets:
  - name: git-ent-secret

